import { PlaylistData, Track, TrackSearchResult } from "../types";

const BACKEND = "https://pobremusic.vercel.app";
export function getCandidateBackendUrls(): string[] { const urls:string[]=[]; try{const c=localStorage.getItem("custom_backend_url");if(c?.startsWith("http"))urls.push(c.replace(/\/+$/, ""));}catch{} if(typeof window!=="undefined"&&window.location?.origin?.startsWith("http"))urls.push(window.location.origin); urls.push(BACKEND); return [...new Set(urls)]; }
export function extractYouTubeVideoId(input:string):string|null{const m=input?.match(/(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|shorts\/))([\w-]{11})/);return m?.[1]||(/^[\w-]{11}$/.test(input?.trim()||"")?input.trim():null)}
export function parseSpotifyInput(input:string):{id:string;type:"playlist"|"album"|"track"|"preset"|"raw"}{const value=input.trim();const m=value.match(/(?:spotify\.com\/[^/]+\/)?(playlist|album|track)\/([A-Za-z0-9]+)/i)||value.match(/spotify:(playlist|album|track):([A-Za-z0-9]+)/i);if(m)return{type:m[1].toLowerCase() as any,id:m[2]};return{type:"raw",id:value.split("?")[0].split("/").pop()?.replace(/[^A-Za-z0-9_-]/g,"")||value}}
export function extractSpotifyPlaylistId(input:string){return parseSpotifyInput(input).id}
async function audiusRequest(params:string){const r=await fetch(`${BACKEND}/api/audius${params}`,{headers:{Accept:"application/json"},cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof data?.error==="string"?data.error:JSON.stringify(data?.error||`Audius ${r.status}`));return data}
function normalizeText(value:string){return String(value||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function matchScore(c:any,title:string,artist:string){const ct=normalizeText(c?.nome_musica),ca=normalizeText(c?.nome_artista),wt=normalizeText(title),wa=normalizeText(artist);let s=0;if(ct===wt)s+=100;else if(ct.includes(wt)||wt.includes(ct))s+=55;if(wa&&ca===wa)s+=100;else if(wa&&(ca.includes(wa)||wa.includes(ca)))s+=60;for(const w of wt.split(" ").filter(Boolean))if(w.length>2&&ct.includes(w))s+=5;return s}
export async function resolveAudiusTrack(nomeMusica:string,nomeArtista:string):Promise<Track>{const queries=[`${nomeMusica} ${nomeArtista}`,nomeMusica].filter((q,i,a)=>q.trim()&&a.indexOf(q)===i);const all:any[]=[];for(const q of queries){try{const d=await audiusRequest(`?q=${encodeURIComponent(q)}`);if(Array.isArray(d?.tracks))all.push(...d.tracks)}catch{}}const best=all.sort((a,b)=>matchScore(b,nomeMusica,nomeArtista)-matchScore(a,nomeMusica,nomeArtista))[0];if(!best?.audioUrl)throw new Error(`Audius não encontrou áudio para ${nomeMusica} — ${nomeArtista}`);return best as Track}
export async function searchMusicTracksClient(query:string):Promise<TrackSearchResult[]>{const q=query.trim();if(!q)return[];const d=await audiusRequest(`?q=${encodeURIComponent(q)}`);return Array.isArray(d?.tracks)?d.tracks:[]}
async function enrichWithAudius(tracks:Track[]):Promise<Track[]>{const result=[...tracks];let cursor=0;const worker=async()=>{while(cursor<result.length){const i=cursor++,t=result[i];try{const m=await resolveAudiusTrack(t.nome_musica,t.nome_artista);const score=matchScore(m,t.nome_musica,t.nome_artista);result[i]=score>=70?{...t,audioUrl:m.audioUrl,origem:"audius",audius_id:m.audius_id,sourceUrl:m.sourceUrl,isStreamable:true}:{...t,origem:"spotify",isStreamable:false}}catch{result[i]={...t,origem:"spotify",isStreamable:false}}}};await Promise.all([worker(),worker(),worker(),worker()]);return result}
export async function fetchPlaylistSafe(urlOrId:string,_spotifyToken?:string|null):Promise<{data:PlaylistData;needsAuth?:boolean}>{const value=urlOrId.trim();const isSpotify=/spotify\.com|spotify:|spoti\.fi|spotify\.link/i.test(value);if(isSpotify||/^[A-Za-z0-9]{15,}$/.test(value)){try{const r=await fetch(`${BACKEND}/api/spotify-playlist?url=${encodeURIComponent(value)}`,{headers:{Accept:"application/json"},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.sucesso||!Array.isArray(d.faixas))return{data:{sucesso:false,playlist_id:value,nome_playlist:"Spotify",descricao:typeof d?.error==="string"?d.error:"Não foi possível carregar a playlist pública do Spotify.",total_faixas:0,faixas:[],modo:"spotify_url_info_public",error:typeof d?.error==="string"?d.error:JSON.stringify(d?.error||d)}};const enriched=await enrichWithAudius(d.faixas as Track[]);const playable=enriched.filter(t=>!!t.audioUrl);return{data:{...d,faixas:enriched,total_faixas:enriched.length,modo:"spotify_metadata_audius_audio",aviso:`${playable.length} de ${enriched.length} faixas possuem áudio disponível no Audius.`,audio_indisponivel:enriched.filter(t=>!t.audioUrl).length}}}catch(e:any){const msg=e?.message||String(e);return{data:{sucesso:false,playlist_id:value,nome_playlist:"Spotify",descricao:msg,total_faixas:0,faixas:[],modo:"spotify_metadata_audius_audio",error:msg}}}}try{const d=await searchMusicTracksClient(value);const tracks:Track[]=d.slice(0,25).map(t=>({...t,origem:"audius"}));if(tracks.length)return{data:{sucesso:true,playlist_id:value,nome_playlist:`Audius: ${value}`,descricao:"Resultados encontrados no Audius",capa_playlist:tracks[0]?.capa||"",total_faixas:tracks.length,faixas:tracks,modo:"audius",aviso:"Reprodução de áudio pelo Audius."}}}catch(e:any){const msg=e?.message||String(e);return{data:{sucesso:false,playlist_id:value,nome_playlist:"Audius",descricao:msg,total_faixas:0,faixas:[],modo:"audius",error:msg}}}return{data:{sucesso:false,playlist_id:value,nome_playlist:"Não encontrado",descricao:"Nenhuma faixa encontrada no Audius. Use uma pesquisa de música ou um link completo de playlist Spotify.",total_faixas:0,faixas:[],modo:"audius",error:"Audius não retornou resultados para esta pesquisa."}}}
export async function resolveYouTubeVideoIdClient(nomeMusica:string,nomeArtista:string,existingVideoId?:string){if(existingVideoId)return existingVideoId;throw new Error(`YouTube desativado. Audius é a fonte de áudio: ${nomeMusica} — ${nomeArtista}`)}
