plugins { id 'com.android.application' }

android { namespace 'com.pobremusic.app'; compileSdk 35
    defaultConfig { applicationId 'com.pobremusic.app'; minSdk 23; targetSdk 35; versionCode 4; versionName 'v1.4' }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation 'androidx.media3:media3-session:1.5.1'
}
